### ISSUE TITLE
el modo oscuro no funciona

### ISSUE THREAD

**Issue by LuchoGirotti** [3-TIC-ORT/proyecto-3-marcelo-ticardo#4]
Hay que hacer que los js del modo oscuro sean iguales a los del modo claro (solamente haciendo que en vez de mandarte a los htmls modo claro te mande a los htmls modo oscuro)
Sino, se puede cambiar la manera en la que se manejan los modos, por ejemplo, haciendo que haya solamente un html y un js para cada página, y dos css que se cambien usando javascript. Esto también serviría para guardar el último modo que se usó en el localstorage

**Comment by lara0m** [comment]
genial
