### ISSUE TITLE
Cosas del diseño que hay que corregir

### ISSUE THREAD

**Issue by NicoleLan** [3-TIC-ORT/proyecto-3-marcelo-ticardo#5]
Hola @lara0m, fue @lucho-girotti quien me dijo que lo haga:

- [x] ¿No es mejor descargar las imágenes de los globos de texto (como SVG) y ponerlas directamente como fondo? para que no se te complique tanto aparte.
No se si soy yo el problema con los tamaños, lo voy a hablar con Pauli porque es bastante diferente y quizás es mi culpa.
- [x] El fondo del título también podes descargarlo,  creo que va a ser más fácil y como son figuras compuestas quizás cuesta más hacerlo con código.
- [x] Cuando te pregunta si queres guía el subtítulo va con bordes rectos y no curvos.
- [x] Los títulos no están centrados
- [x] Ya cambié las tipografías, (Jacques Francois) y de los botones es "Kite One"
- [x] Los botones en general están muy arriba, aunque repito, puede ser mi culpa.
- [x] Falta los símbolos del modo claro/oscuro la página inicial.

**Comment by lara0m** [comment]
Ahí corrijo y agrego lo que me dijiste. Sobre las imagenes del globo de
texto, podemos hacerlo pero el tema que ya hice los globos (si preferis la
imagen por el tema de la estetica, no hay ningun problema)

**Comment by LuchoGirotti** [comment]
Ya fueron corregidos todos los problemas (gracias @lara0m)
